### ISSUE TITLE
Better shell command for patching

### ISSUE THREAD

**Issue by dirk-olmes** [hhoffstaette/kernel-patches#1]
I use the following comand for kernel patching:

```
foreach f (~/Projekte/Linux/kernel-patches/4.1/*.patch);
    patch -p1 -s < $f || echo "could not apply $f";
end
```

As opposed to the command mentioned in the README, it will print any patch file that did not apply cleanly.

**Comment by hhoffstaette** [comment]
This is what I use as well; the line in the README is mostly for simplicity.

**Comment by hhoffstaette** [comment]
I've added the error handling to the README. Thanks. :)
