### ISSUE TITLE
patches fails to apply when using --fuzz=0

### ISSUE THREAD

**Issue by ghibo** [hhoffstaette/kernel-patches#11]
Great job Holger, however, would be possible to have the patches rediffed, so they work when they are applied with --fuzz=0 as patch command argument in apply.sh? I noticed that some patchset doesn't apply correctly when applied with --fuzz=0 (e.g. because some function around the code has even changed the number of arguments). This happens in especially the net rack loss detection patchset.

**Comment by hhoffstaette** [comment]
Thanks for the feedback! I usually try to massage a context when necessary so that the patch applies without fuzz (precisely because of the potential to mess things up otherwise), but may have missed some. I'll look into it but it will take a few days; it's mostly cosmetic after all.

**Comment by hhoffstaette** [comment]
This was easier than expected and is now in 4.9.35. :)

**Comment by ghibo** [comment]
Great. It works!
