### ISSUE TITLE
Revert net-20170118-remove-usage-of-net_device-last_rx-member.patch:-

### ISSUE THREAD

**Issue by ghibo** [hhoffstaette/kernel-patches#12]
Would be possible to revert/remove from the patchset the patch net-20170118-remove-usage-of-net_device-last_rx-member.patch, at least until it's not merged into upstream 4.9.x? Actually it changes the common structure net_device (see file include/linux/netdevice.h) removing one member, i.e. 'last_rx'. As a side effect it breaks the building of some 3rd party driver (which needs to be fixed in the same ways) such as ndiswrapper or broadcom-wl which still refers to last_rx member somewhere.

**Comment by hhoffstaette** [comment]
Hi, thanks for the feedback. This patch will never be merged back into 4.9 upstream. Off the top of my head I don't remember why I added it (probably a prerequisite for others to apply cleanly), but out-of-tree drivers have always been at a disadvantage. That being said, I'll look into it.

**Comment by hhoffstaette** [comment]
So it turns out that this patch is not a prerequisite and can be reverted without problem. I think it just looked good at the time. ;-)
I'll revert it for the next release (.39, currently in -rc1), due tomorrow or so.

**Comment by ghibo** [comment]
OK. Should be necessary in the future, and the copy of jiffies are really cosmetic or abused, maybe the only part altering the structure members in include/linux/netdevice.h could be left out. Anyway for .39, just in the case you haven't yet prepared it, it seems that these patches:

mm-20170627-fix-crash-due-to-race-in-MADV_FREE-handling.patch
net-20170621-avoid-unregistering-inet6_dev-for-loopback.patch
net-20170621-only-call-ip6_route_dev_notify-once-for-NETDEV_UNREGISTER.patch
net-20170624-reset-sk_rx_dst-in-tcp_disconnect.patch
net-20170629-handle-NAPI_GRO_FREE_STOLEN_HEAD-case-also-in-napi_frags_finish.patch
net-20170703-fix-slab-out-of-bounds-in-netdev_stats_to_stats64.patch
sched-20170710-001-export-for_each_cpu_wrap.patch

need to be removed to as they are going to be merged upstream.

**Comment by hhoffstaette** [comment]
All already done. :)

**Comment by ghibo** [comment]
:-)
