### ISSUE TITLE
Error in "vfs-20200512-keep-inodes-with-page-cache-off-the-inode-shrinker-LRU.patch"

### ISSUE THREAD

**Issue by torvic9** [hhoffstaette/kernel-patches#15]
Third hunk should be
`inode_pages_clear(mapping->host)`
and
`inode_pages_set(mapping->host)`

instead of `mapping->inode`.

Else it throws an error if DAX is enabled:

```
fs/dax.c:556:30: error: no member named 'inode' in 'struct address_space'
                inode_pages_clear(mapping->inode);
                                  ~~~~~~~  ^
fs/dax.c:558:28: error: no member named 'inode' in 'struct address_space'
                inode_pages_set(mapping->inode);
```

(tested with clang-10)

**Comment by hhoffstaette** [comment]
Sorry for the delay, it seems Github's changes to notifications no longer send emails for issues.
I'll look into the change immediately.

**Comment by hhoffstaette** [comment]
You're [completely right](https://lkml.org/lkml/2020/5/14/362) - good catch. I don't use DAX and therefore didn't catch it either.

**Comment by hhoffstaette** [comment]
Merged, thanks!
