### ISSUE TITLE
Missing closing bracket in sched-prjc-v6.6-r0.patch

### ISSUE THREAD

**Issue by whrvt** [hhoffstaette/kernel-patches#18]
In `6.6/sched-prjc-v6.6-r0.patch`, there is a missing closing bracket on line 5009 in the `sched_tick_remote(...)` function. The "if" statement above has an opening bracket, but no closing bracket.

This was probably missed because it only shows up when compiling with the CONFIG_NO_HZ_FULL option set.

**Comment by hhoffstaette** [comment]
Thanks for reporting! I've pushed -r1 with two fixes from zen-kernel.
