### ISSUE TITLE
BFQ and WBT

### ISSUE THREAD

**Issue by torvic9** [hhoffstaette/kernel-patches#9]
Hi Holger,
Thanks for your excellent patch series.
I'd like to make you aware of a newer version of the "disable WBT for non-root cgroup" patch. Maybe you could include it in your series if it is compatible with 4.9 (it should be). Or is it already there?
See here: https://github.com/pfactum/pf-kernel/commit/154a26bdff29d02c3e31c80b5d1042b03fbcd2fa
And here: https://groups.google.com/forum/#!topic/bfq-iosched/N9htMk5EAJ8

**Comment by hhoffstaette** [comment]
The patch would apply but does not build because ```wbt_disable_default``` does not exist in 4.9.x:
```
block/bfq-iosched.c: In function 'bfq_set_request':
block/bfq-iosched.c:4632:3: error: implicit declaration of function 'wbt_disable_default' [-Werror=implicit-function-declaration]
   wbt_disable_default(q);
   ^~~~~~~~~~~~~~~~~~~
```

So since it's not critical I'll just leave the existing patch in.
